import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'rsuite/dist/rsuite.min.css';
import "bootstrap/dist/css/bootstrap.min.css";
import { CustomProvider } from "rsuite";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Pet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>
          {children}
        </CustomProvider>
      </body>
    </html>
  );
}
